---
# vars file for sssd

sss_packages:
  - authconfig
  - sssd

sss_allowed_groups:
  - admins

sss_ldap_hosts:
  - '{{ trix_ctrl_hostname }}.{{ trix_domain }}'

sss_filter_enabled: true

ca_certificate_path: /etc/openldap/certs/
ldap_conf: /etc/openldap/ldap.conf

