---
# vars file for bind

bind_packages:
  - bind

# luna handles the forwarders - Antoine
# the below will only go into resolv.conf
bind_dns_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'

bind_dnssec_enable: 'no'
bind_db_path: '/var/named'

resolv_server: '127.0.0.1'
resolv_search_domains: '{{ trix_domain }} ipmi'

trix_local: ""
