---
- name: run update_ood_portal
  command: '/opt/ood/ood-portal-generator/sbin/update_ood_portal -f'
  register: command_result
  failed_when: "'Completed successfully!' not in command_result.stdout"
  notify:
    - restart httpd24-httpd
    - restart httpd24-htcacheclean
    - restart httpd
    - restart htcacheclean
    - restart ondemand-dex

- name: restart ondemand-dex
  systemd:
    name: ondemand-dex
    state: restarted

- name: restart httpd24-httpd
  systemd:
    name: httpd24-httpd
    state: restarted
  when: ansible_distribution == "CentOS"

- name: restart httpd24-htcacheclean
  systemd:
    name: httpd24-htcacheclean
    state: restarted
  when: ansible_distribution == "CentOS"

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
  when: ansible_distribution == "Rocky"

- name: restart htcacheclean
  systemd:
    name: htcacheclean
    state: restarted
  when: ansible_distribution == "Rocky"