---
stages:
  - installation 

ansible-rocky8:
  stage: installation
  when: manual
  tags:
    - luna2
  image:
    name: geerlingguy/docker-rockylinux8-ansible
  script:
    - ls
    - hostname controller1.cluster
    - bash prepare.sh
    - cd site   
    - cp -a hosts.example hosts
    - cp -a group_vars/all.yml.example group_vars/all.yml 
    - sed -i "s/controller1/${HOSTNAME}" hosts
    - sed -i "s/controller1/${HOSTNAME}" group_vars/all.yml 
    - ansible-playbook controller.yml
    - ansible-playbook compute-redhat.yml

ansible-rocky9:
  stage: installation
  when: manual
  tags:
    - luna2
  image:
    name: geerlingguy/docker-rockylinux9-ansible
  script:
    - cd roles/common
