---
stages:
  - installation 

ansible-rocky8:
  stage: installation
  when: manual
  tags:
    - luna2
  image:
    name: geerlingguy/docker-rockylinux8-ansible
  script:
    - ls
    - bash prepare.sh
    - cd site   
    - cp -a hosts.example hosts
    - cp -a group_vars/all.yml.example group_vars/all.yml 

ansible-rocky9:
  stage: installation
  when: manual
  tags:
    - luna2
  image:
    name: geerlingguy/docker-rockylinux9-ansible
  script:
    - cd roles/common
