---

required_packages:
  - "debootstrap"
  - "zstd"

ubuntu_distribution_source: ftp://ftp.nluug.nl/pub/os/Linux/distr/ubuntu/

ubuntu_distribution_release: jammy

image_core_packages:
  - python3
  - mc 
  - e2fsprogs 
  - xfsprogs 
  - net-tools 
  - tar 
  - bzip2 
  - lbzip2 
  - parted 
  - gpg 
  - ipmitool
  - linux-image
  - ssh
  - curl

