---
# tasks file for nfs-mounts

- name: Install nfs packages
  yum:
    name: '{{ nfs_packages }}'
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install nfs packages
  deb:
    name: '{{ nfs_packages }}'
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure mountpoints exist
  file:
    path: '{{ item.path }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items: '{{ nfs_mounts }}'

- name: Setup NFS mounts
  mount:
    path: '{{ item.path }}'
    src: '{{ item.remote }}'
    fstype: 'nfs'
    opts: '{{ item.options }},proto={{ "rdma" if nfs_enable_rdma else "tcp" }}'
    state: '{{ "present" if ansible_connection in "chroot" else "mounted" }}'
  with_items: '{{ nfs_mounts }}'
