---
# tasks file for obol

- name: Generate openldap root password and save it to /etc/trinity/passwords
  set_fact:
    tmp_pwd: "{{ lookup('password',
                          '/etc/trinity/passwords/openldap/root.txt
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Get openldap root password from /etc/trinity/passwords
  set_fact:
    openldap_root_pwd: "{{ lookup('password',
                          '/etc/trinity/passwords/openldap/root.txt
                           chars=ascii_letters,digits,hexdigits') }}"

- block:
  - name: Install obol dependency packages
    yum:
      name: '{{ obol_packages }}'
      state: present
    tags: install-only

#  - name: Install obol pip dependencies
#    pip:
#      name:
#        - python-ldap
#        - retrying
#      executable: pip2

  - name: Install obol pip dependencies
    pip:
      name:
        - python-ldap
        - retrying
      executable: pip3

  - name: Install obol to /usr/local/bin
    copy:
      src: 'obol'
      dest: '/usr/local/bin'
      owner: 'root'
      group: 'root'
      mode: '0750'

  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int < 9

#- name: Determine the installed python3 version
#  shell: "rpm -q python3|grep -oE '[0-9]+\\.[0-9]+'|head -n1"
#  register: python3_version

#- name: Install Obol
#  shell: "pip3 install obol"
#  when: python3_version is defined

#- name: Copy Obol patch
#  copy:
#    src: 'obol.patch'
#    dest: '/tmp/'

#- name: Patch Obol to be python3 compliant
#  shell: "patch /usr/local/lib/python{{ python3_version.stdout }}/site-packages/obol/main.py < /tmp/obol.patch"
#  when: python3_version is defined

- name: Add default configuration to {{ obol_conf_path }}
  template:
    src: 'obol.conf.j2'
    dest: '{{ obol_conf_path }}/obol.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Add link to the configuration file in /etc
  file:
    src: '{{ obol_conf_path }}'
    dest: '/etc/'
    state: link
  when: obol_conf_path|string not in '/etc'

