---
- hosts: controllers

  roles:
  - role: trinity/init
    tags: init

  - role: ansible/write_facts
    tags: init

  - role: ansible/read_facts
    tags: init

  - role: trinity/image-create-ubuntu
    tags: image-create
    when: primary
