---

drbd_ctrl1_ip: '{{ trix_ctrl1_ip }}'
drbd_ctrl2_ip: '{{ trix_ctrl2_ip }}'
drbd_ctrl1_device: /dev/drbd1
drbd_ctrl2_device: '{{ drbd_ctrl1_device }}'
drbd_ctrl1_disk: '{{ shared_fs_device }}'
drbd_ctrl2_disk: '{{ drbd_ctrl1_disk }}'
drbd_shared_resource_name: trinity_disk

drbd_packages:
  - https://mirror.rackspace.com/elrepo/elrepo/el7/x86_64/RPMS/kmod-drbd90-9.0.22-2.el7_8.elrepo.x86_64.rpm
  - https://mirror.rackspace.com/elrepo/elrepo/el7/x86_64/RPMS/drbd90-utils-9.12.2-1.el7.elrepo.x86_64.rpm
  #- kmod-drbd90
  #- drbd90-utils
