---
# tasks file for ood-vnc
- name: Install ood-vnc requirements ( on machine whoose desktop is forwarded )
  block:
    - name: Install required yum repos
      yum:
        name: "{{ item.name }}"
        state: present
        disable_gpg_check: "{{ item.no_gpgcheck | default(False) }}"
      with_items: "{{ ood_compute_repository_rpms }}"

    - name: Install required yum packages
      yum:
        name: 
          - "@{{ood_vnc_desktop_package}}" # -> groupinstall xfce
          - turbovnc
          - python3-websockify
        state: present

    # - name: Render ood-vnc-module-load.sh template file
    #   template:
    #     src: 'ood-vnc-module-load.sh.j2'
    #     dest:  /etc/profile.d/zz_trinityx_ood_vnc.sh
    #     mode: '0644'
    #     owner: root
    #     group: root
    
  when: 
    - enable_ood_vnc == true
    - ansible_connection in 'chroot'

# This should be done by controller because /trinity/shared is not mounted on compute node
- name: Render ood-vnc-module.tcl template file
  template:
    src: 'ood-vnc-module.tcl.j2'
    dest: '{{ trix_shared }}/modulefiles/ood-vnc.tcl'
    mode: '0644'
    owner: root
    group: root
  
  when: 
    - enable_ood_vnc == true
    - ansible_connection not in 'chroot'
