---
# handler file for luna

- name: restart xinetd
  service:
    name: xinetd
    state: restarted
#  when: primary|default(True)

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
#  when: primary|default(True)

- name: restart nginx
  service:
    name: nginx
    state: restarted
#  when: primary|default(True)

- name: restart luna2-daemon
  service:
    name: luna2-daemon
    state: restarted
#  when: primary|default(True)

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
