---
# handler file for luna

- name: restart xinetd
  service:
    name: xinetd
    state: restarted
#  when: primary|default(True)

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
#  when: primary|default(True)

- name: reload nginx
  service:
    name: nginx
    state: reloaded
#  when: primary|default(True)

- name: restart luna2-daemon
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - luna2-daemon
#  when: primary|default(True)

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
