---

- name: Add beegfs pacemaker resources
  pcs_resource:
    name: 'beegfs-mgmtd'
    resource_class: 'systemd'
    resource_type: 'systemd:beegfs-mgmtd'
    options: 'op monitor interval=30 --group Trinity-stack'
    state: present
  when: ha|default(False)
  tags: pcs
