---

- name: Install RabbitMQ Repo
  yum_repository:
    name: CV-RabbitMQ
    description: RabbitMQ Server repository
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/8/x86_64
    gpgkey: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    gpgcheck: false
    repo_gpgcheck: false

- name: Install erlang repo
  yum_repository:
    name: CV-erlang-22
    description: Erlang 22 repository
    baseurl: https://packagecloud.io/rabbitmq/erlang/el/8/x86_64
    gpgkey: https://packagecloud.io/rabbitmq/erlang/gpgkey
    gpgcheck: false
    repo_gpgcheck: false

- name: Install RabbitMQ Server
  yum:
    name: rabbitmq-server
    state: installed

- name: Set erlang cookie
  copy:
    src: erlang.cookie
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: '0400'
  notify: restart rabbitmq-server

- name: Start and enable rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: make sure rabbitmq app is up
  command: rabbitmqctl start_app
  changed_when: false

- include_tasks: setup_rabbitmq.yml
