---
- name: Create sensu vhost
  rabbitmq_vhost:
    name: /sensu
    state: present


- name: ClusterVision user
  rabbitmq_user:
    user: clustervision
    password: itops
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: ClusterVision user
  rabbitmq_user:
    user: clustervision
    password: itops
    tags: administrator
    vhost: /sensu
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Sensu user
  rabbitmq_user:
    user: sensu
    password: m0nit0ring
    vhost: /sensu
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
