---
# Install additional packages and tunables

- name: Install prereq packages
  yum:
    name: '{{ packages_packages }}'
    state: present
  tags: install-only

- name: Install additional packages
  yum:
    name: '{{ tunables_packages }}'
    state: present
  tags: install-only
  with_items: '{{ tunables_packages }}'

- name: Enable haveged service
  service:
    name: haveged
    enabled: yes

- name: Start haveged service
  service:
    name: haveged
    state: started
  when: ansible_connection not in 'lchroot'
