---
# tasks file for slurm
- name: Install ohpc-release
  yum:
    name: https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
    state: installed

- name: Install pbspro-server
  yum:
    name: pbspro-server-ohpc
    state: present
  tags: install-only
  when: on_controller|default(True)

- name: Install pbspro-execution
  yum:
    name: pbspro-execution-ohpc
    state: present
  tags: install-only
  when: compute|default(False)

- name: Configure PBSPro
  template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
  notify: restart pbs

- name: Configure mom_priv
  template:
    src: mom_priv_config.j2
    dest: /var/spool/pbs/mom_priv/config
  notify: restart pbs
  when: compute|default(False)

- name: Enable and start PBS
  systemd:
    name: pbs
    enabled: "yes"
    state: started
