---
# tasks file for pbspro
- name: Create OpenHPC repo
  ansible.builtin.yum_repository:
    name: "openhpc"
    description: "OpenHPC 3.0 repo hosted by CV"
    baseurl: "https://updates.clustervision.com/trinityx/external/openhpc/{{ ansible_os_family|lower }}/{{ ansible_distribution_major_version }}"
    gpgcheck: false
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int > 8

- block:
  - name: Create OpenHPC repo
    ansible.builtin.yum_repository:
      name: "openhpc"
      description: "OpenHPC repo"
      baseurl: "{{ openhpc_release_repo }}"
      gpgcheck: false
    when: openhpc_release_repo is defined

  - name: Install ohpc-release
    yum:
      name: "{{ openhpc_release_rpm }}"
      state: installed
      disable_gpg_check: true
    when: openhpc_release_repo is undefined
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int < 9

- name: Install Openpbs-server
  yum:
    name: openpbs-server-ohpc
    state: present
  tags: install-only
  when: on_controller|default(True)

- name: Install openpbs-execution-ohpc
  yum:
    name: openpbs-execution-ohpc
    state: present
  tags: install-only
  when: compute|default(False)

- name: Configure PBSPro
  template:
    src: pbs.conf.j2
    dest: /etc/pbs.conf
  notify: restart pbs

- name: Configure mom_priv
  template:
    src: mom_priv_config.j2
    dest: /var/spool/pbs/mom_priv/config
  notify: restart pbs
  when: compute|default(False)

- name: Enable and start PBS
  systemd:
    name: pbs
    enabled: "yes"
    state: started
