---

- name: Synchronizing /etc/trinity/passwords between controllers
  synchronize:
    src: /etc/trinity/passwords
    dest: /etc/trinity
    archive: yes
    delete: yes

- name: Refresh exportfs
  shell: "exportfs -a"
  ignore_errors: yes

