---
- name: Copy logrotate configuration files
  copy:
    src: '{{ item }}'
    dest: '/etc/logrotate.d/{{ item }}'
    force: "no"
  with_items:
    - trinityx
    - uchiwa
    - sensu
    - slurm
    - influxdb
    - telegraf
    - luna

- name: Changing owner and group for logrotate config
  file:
    path: '/etc/logrotate.d/{{ item }}'
    owner: root
    group: root
  with_items:
    - trinityx
    - uchiwa
    - sensu
    - slurm
    - influxdb
    - telegraf
    - luna

- name: Restart logrotate
  notify: restart logrotate
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int > 8

