---
- name: Copy logrotate configuration files
  copy:
    src: '{{ item }}'
    dest: '/etc/logrotate.d/{{ item }}'
    force: "no"
  with_items:
    - trinityx
    - uchiwa
    - sensu
    - slurm
    - influxdb
    - telegraf
    - luna
