---
# vars file for nfs

nfs_packages:
  - nfs-utils

nfs_enable_rdma: false
nfs_mounts:
  - path: '/trinity/shared'
    remote: '{{ trix_ctrl_hostname }}:/trinity/shared'
    options: 'defaults,nfsvers=4,ro,retrans=4'
