---
- name: Install ohpc-release
  yum:
    name: https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
    state: installed

- name: Install ohpc-base
  yum:
    name: ohpc-base
    state: installed
