---
- name: Install ohpc-release
  yum:
    name: https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
    state: installed

- name: Install ohpc-base
  yum:
    name: ohpc-base
    state: installed

- name: Update NFS exports
  template:
    src:  OHPC_exports
    dest: '{{ nfs_exports_path }}/ohpc.exports'
  when: primary | default(True)
  notify:
    - Export NFS

- name: Add link to the exports file in /etc/exports.d
  file:
    src: '{{ nfs_exports_path }}/ohpc.exports'
    dest: '/etc/exports.d/ohpc.exports'
    state: link
    force: yes
  notify:
    - Export NFS

