---

- name: Set HA controllers' domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{trix_ctrl1_ip}}    {{trix_ctrl1_hostname}}.{{trix_domain}} {{trix_ctrl1_hostname}}
      {{trix_ctrl2_ip}}    {{trix_ctrl2_hostname}}.{{trix_domain}} {{trix_ctrl2_hostname}}
      {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
#      {{ ansible_default_ipv4.address }} {{ ansible_fqdn.split('.') | first }} {{ ansible_fqdn }}
  when: ha|default(False)

- name: Set non-HA controller's domain name
  blockinfile:
    path: /etc/hosts
    block: |
      {{trix_ctrl_ip}}    {{trix_ctrl_hostname}}.{{trix_domain}} {{trix_ctrl_hostname}}
#      {{ ansible_default_ipv4.address }} {{ ansible_fqdn.split('.') | first }} {{ ansible_fqdn }}
  when: not ha|default(False)


- name: Re-gather facts
  action: setup

