---
# vars file for luna2

luna2_packages:
  - luna2-python
#  - luna2-daemon
#  - luna2-cli

required_packages:
  - dhcp-server
  - xinetd
  - sqlite
  - dos2unix
  - tftp-server

luna2_daemon_pip: daemon-2.0-py3-none-any.whl
luna2_cli_pip: luna-2.0-py3-none-any.whl
#luna2_cli_pip: luna2_cli-2.0-py3-none-any.whl
#luna2_cli_pip: luna2_cli-2.0.27-py3-none-any.whl

luna2_named_include_file: /etc/named.luna.zones
luna2_named_zone_dir: /var/lib/named

luna2_cluster:
  frontend_address: '{{ trix_ctrl_ip }}'
  networks:
  - name: '{{ trix_domain }}'
    ip: '{{ trix_cluster_net }}'
    prefix: '{{ trix_cluster_netprefix }}'
    start_ip: '{{ trix_cluster_dhcp_start }}'
    end_ip:  '{{ trix_cluster_dhcp_end }}'
  - name: 'ipmi'
    ip: '10.148.0.0'
    prefix: '16'
  - name: 'ib'
    ip: '10.149.0.0'
    prefix: '16'

luna2_noarch_pip_repository: https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/pip/stable

luna2_key: CwSQcHNqiLSHXQaCDtAF2414e3muXgmpht6ocVA2xGs=

