---

- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Create dir for compute image
  file:
    name: "{{ image_path }}"
    state: directory

- name: Set facts
  set_fact:
    data:
      trix_ctrl_hostname: "{{ trix_ctrl_hostname }}"
      trix_ctrl_ip: "{{ trix_ctrl_ip }}"

- name: Create facts file
  copy:
    dest: "{{ image_path }}/facts.dat"
    content: "{{ data }}"


