---

- name: Get image path
  set_fact:
    image_path: "{{ trix_images }}/{{ image_name }}"

- name: Remove existing facts file
  file:
    path: "{{ image_path }}/facts.dat"
    state: absent

- name: Create facts file
  file:
    path: "{{ image_path }}/facts.dat"
    state: touch

- name: Add trix_ctrl_hostname to facts file
  lineinfile:
    path: "{{ image_path }}/facts.dat"
    line: "trix_ctrl_hostname:{{ trix_ctrl_hostname }}"

- name: Add trix_ctrl_ip to facts file
  lineinfile:
    path: "{{ image_path }}/facts.dat"
    line: "trix_ctrl_ip:{{ trix_ctrl_ip }}"
